// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypjxymlnxvbnhzsrchfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwanh5bWxueHZibmh6c3JjaGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODQyNTMsImV4cCI6MjA3MDA2MDI1M30.LEUPj8PeVuzfAYbd1PsBs6nMnXE0OP0zCtszSaSxH_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});